# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '18af29ef86ffff0eca7b0114af4041c0446cc26d'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1
  host: staging-collector.newrelic.com
#
# Agent Configuration:
#
agents:
  # this is where configuration for agents belongs
  example:
    hertz: 1000
