# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1
#
# Agent Configuration:
#
agents:
# Configuration for RabbitMQ
  rabbitmq:
    # Defailt is http://guest:guest@localhost:55672
    # Must enable rabbit management plugin
    management_api_url: http://guest:guest@localhost:55672
# Configuration for vFabric Web Server/mod_bmx
  httpd_mod_bmx:
      -
        hostname: localhost
        hostport: 80
        # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
        debug: false
        # Set "testrun: true" to use input from local text/html files. Only parses input once, then quits.
        testrun: false
      -
        hostname: www
        hostport: 80
        # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
        debug: false
        # Set "testrun: true" to use input from local text/html files. Only parses input once, then quits.
        testrun: false

